### ISSUE TITLE
RestDocs 설정 및 적용

### ISSUE THREAD

**Issue by cxxxtxxyxx** [livable-final/server#82]
- 실질적 적용 여부가 미지수임에 따른 보류

**Comment by khsrla9806** [comment]
REST DOCS와의 전쟁에서 승리하시길 바랍니다.

**Comment by cxxxtxxyxx** [comment]
> REST DOCS와의 전쟁에서 승리하시길 바랍니다.

ㅋㅋㅋㅋㅋ 적용은 했는데 원하는대로는 실패했읍니담..ㅠ
